name: xeus-lua
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  # Host dependencies
  - xeus>=6.0,<=7
  - xeus-zmq>=4.0,<5
  - nlohmann_json
  - cppzmq
  - lua>=5.2.0,<5.5
  - openlibm # [linux]
  - xwidgets >=0.30.0
  - xcanvas>=0.7.0
  # to try it out
  - jupyterlab
  # Test dependencies
  - pytest
  - nbval
  - ipympl
  - jupyter_kernel_test
